version: '3.9'

services:
  app:
    build: .
    container_name: mood-journal-api
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://journal_user:journal_pass@db:5432/journal_db
    depends_on:
      - db
    networks:
      - test-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: journal_user
      POSTGRES_PASSWORD: journal_pass
      POSTGRES_DB: journal_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test-net

  tests:
    build: ../.tests/mood_journal_d3fbf117-4429-4933-a8aa-cc68fc2c5c46
    container_name: mood-journal-tests
    depends_on:
      app:
        condition: service_healthy
    networks:
      - test-net
    volumes:
      - ../.tests/mood_journal_d3fbf117-4429-4933-a8aa-cc68fc2c5c46:/app

networks:
  test-net:
    driver: bridge

volumes:
  postgres_data: 